function [ ] = my_plot(t, label, my_title, varargins)
%
% my_plot(t, label, my_title, varargins)
%
% vargins = {line1, line2, legend1, legend2, lineStyle1, lineStyle2}
% Works with up to 7 lines

figure('Units', 'pixels', ...
    'Position', [500 100 500 375]);
hold on;


colors =    [0    0.4470    0.7410;...
            0.8500    0.3250    0.0980;...
            0.9290    0.6940    0.1250;...
            0.4940    0.1840    0.5560;...
            0.4660    0.6740    0.1880;...
            0.3010    0.7450    0.9330;...
            0.6350    0.0780    0.1840];

nSignals = length(varargins)/3;
storeLines = cell(2, nSignals);

for  i = 1:nSignals
    tempLine = line(t, varargins{i});
    set(tempLine   , ...
	'LineWidth'     , 1.5	, ...
	'Color'         , colors(i,:),...
    'LineStyle'     , varargins{i+2*nSignals});

    storeLines(:, i) = [{tempLine}; varargins(i+1*nSignals)];
end

hTitle  = title (my_title);
hXLabel = xlabel('Time (s)');
hYLabel = ylabel(label);

hLegend = legend([storeLines{1, :}], ...
    storeLines(2, :), ...
    'location', 'NorthEast');

set(hLegend						, ...
	'Interpreter', 'latex');

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hLegend, gca]             , ...
    'FontSize'   , 12           );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          );
set( hTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );

end

